#name: CI
#
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#
#permissions:
#  actions: read
#  contents: read
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#
#      - uses: actions/setup-node@v4
#        with:
#          node-version: 20
#          cache: 'npm'
#
#      - name: Install Tauri CLI
#        run: cargo install tauri-cli
#
#      - name: Install system dependencies (GTK/WebKit/GLib/etc)
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y \
#            libwebkit2gtk-4.0-dev \
#            build-essential \
#            curl \
#            wget \
#            file \
#            libssl-dev \
#            libgtk-3-dev \
#            libayatana-appindicator3-dev \
#            librsvg2-dev \
#            pkg-config \
#            libglib2.0-dev \
#            libgdk-pixbuf2.0-dev
#
#      - name: Install JS/TS dependencies
#        run: npm ci --legacy-peer-deps
#
#      - name: Install Tauri app dependencies
#        run: |
#          cd apps/tauri-app
#          yarn install
#          cd ../../
#
#      - name: Build all Nx targets (lint, test, build)
#        run: npx nx run-many -t lint test build
#
#      - name: Fix CI if needed
#        if: always()
#        run: npx nx fix-ci
